[package]
name = "oak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
colored = "2.0.0"
xxhash-rust = { version = "0.8.7", features = ["xxh3"] }
