name: ci

on: [push]

jobs:
  code_style: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Install dependencies
        run: go install github.com/segmentio/golines@latest

      - name: Check gofmt
        run: if [ "$(gofmt -s -d . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Check golines
        run: if [ "$(golines -m 120 --dry-run . | wc -l)" -gt 0 ]; then exit 1; fi

  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
     
      - name: Install dependencies
        run: go get .
     
      - name: Test
        run: go test -v 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
     
      - name: Install dependencies
        run: go get .
     
      - name: Build
        run: go build -v 
